// ---------------------------------------------------------------------------
// Phase C opcode registry — the SINGLE source of truth for the 0x20–0x3F space
// (spec §5.2). No feature may mint an opcode or a per-family `kind` byte outside
// this file; the exhaustiveness + kind-uniqueness tests in protocol.test.ts are
// the tripwire. 0x00–0x0F are Phase A game; 0x10–0x1F are Phase B voice.
//
// Byte layouts for the HOT binary families are normative in spec Appendix B and
// mirrored by the codec at the bottom of this file; the golden (hex, fields)
// pairs are machine-generated by tools/gen-goldens.mjs (hand hex forbidden).
// ---------------------------------------------------------------------------

/**
 * The 0x20–0x3F Phase C opcode assignments (spec §5.2). 0x32–0x35 are minted now
 * for registry stability but carry no traffic until their tasks land (C25 / C26 /
 * C32 / C34). 0x36–0x3F are reserved-free — Phase D mints from there when planned.
 */
export const OPCODES = {
  TIER_HELLO: 0x20,
  PHASE_STATE: 0x21,
  DIRECTOR: 0x22,
  ENV_STATE: 0x23,
  THEME_SET: 0x24,
  VOTE: 0x25,
  WISP: 0x26,
  SHOWPIECE: 0x27,
  PLAYER_SCALE: 0x28,
  MUSIC: 0x29,
  CROWD_CUE: 0x2a,
  GLYPH: 0x2b,
  REEL: 0x2c,
  GRAB_REJECTED: 0x2d,
  STATS_CARD: 0x2e,
  METRICS_PING: 0x2f,
  CLOCK_PING: 0x30,
  CLOCK_PONG: 0x31,
  AUDIENCE_STATE: 0x32,
  CASTER_LINE: 0x33,
  TELEKINESIS: 0x34,
  BUILD: 0x35,
} as const;

export type OpcodeName = keyof typeof OPCODES;
export type Opcode = (typeof OPCODES)[OpcodeName];

/** Sorted list of every minted opcode byte (used by exhaustiveness checks). */
export const ALL_OPCODES: readonly number[] = Object.freeze(
  (Object.values(OPCODES) as number[]).slice().sort((a, b) => a - b)
);

/** True iff `byte` is inside the Phase C opcode window (0x20–0x3F). */
export function isPhaseCOpcode(byte: number): boolean {
  return byte >= 0x20 && byte <= 0x3f;
}

/** True iff `byte` is a currently-minted Phase C opcode (0x36–0x3F return false). */
export function isKnownPhaseCOpcode(byte: number): boolean {
  return (ALL_OPCODES as number[]).includes(byte);
}

// ---------------------------------------------------------------------------
// Per-family kind enums. Later tasks ADD kinds here (never locally): C29 adds
// STAGE_XRAY / C31 SAVE_CLIP to DIRECTOR, C27 adds WAVE to SHOWPIECE, C32 fleshes
// out TELEKINESIS, C34 adds the real BUILD kinds. Single-kind families use 0x00.
// ---------------------------------------------------------------------------

/**
 * 0x22 DIRECTOR family (C31 adds SAVE_CLIP). C29 (F18 X-Ray Broadcast, spec
 * §7.18) adds `STAGE_XRAY` — the registry-reserved kind byte for the director-
 * console x-ray trigger. Honest protocol delta (spec §7.18: "zero new opcodes
 * … one kind byte"): the wire transport is the EXISTING JSON `director-cmd`
 * (`cmd: 'STAGE_XRAY'`, gated by the existing ownerToken `meta.director` check)
 * relayed to the room as `director-msg { kind: 'STAGE_XRAY' }` via the existing
 * `broadcastOpcodeToTiers(DIRECTOR, …)` seam — the SAME pattern PANIC already
 * rides. This entry only reserves the byte for registry completeness/exhaustiveness;
 * no new binary layout is introduced.
 *
 * C31 (F20 Neon Clip Machine, spec §7.20) adds `SAVE_CLIP` — the console's SAVE
 * CLIP override. The stage-LOCAL hotkey is the PRIMARY trigger (zero protocol,
 * mirrors STAGE_XRAY); a phone director console fires `director-cmd {cmd:
 * 'SAVE_CLIP'}` which relays to the stage as `director-msg {kind:'SAVE_CLIP'}`
 * via the SAME `broadcastOpcodeToTiers(DIRECTOR, …)` seam. The stage owns ALL
 * recording state locally (clipId minting, the recorder state machine, upload) —
 * the server is a pure relay, never authoritative over it. No new binary layout.
 */
export const DIRECTOR_KIND = {
  CMD: 0x00,
  CATALOG: 0x01,
  ACK: 0x02,
  STAGE_XRAY: 0x03,
  SAVE_CLIP: 0x04,
} as const;

/** 0x25 VOTE family. */
export const VOTE_KIND = { OPEN: 0x00, CAST: 0x01, TALLY: 0x02, RESULT: 0x03 } as const;

/** 0x26 WISP family. WISP_POSE (kind 0x02) has a normative Appendix B layout. */
export const WISP_KIND = {
  JOIN: 0x00,
  LEAVE: 0x01,
  POSE: 0x02,
  PULSE: 0x03,
  ROSTER: 0x04,
} as const;

/**
 * 0x27 SHOWPIECE family. C27 adds WAVE (0x05) — the escalating Siege-Waves
 * narrative ({waveIndex, waveEndsAt}; §7.16). WAVE is a PURELY ADDITIVE kind: a
 * client that predates C27 ignores it (the unknown-kind-ignore degrade rung — the
 * if/else kind dispatch has no throwing default) and still renders a coherent
 * siege from START/STATE/END, with the wave BANNER arriving free on ENV_STATE.
 */
export const SHOWPIECE_KIND = {
  START: 0x00,
  STATE: 0x01,
  END: 0x02,
  MET_LAUNCH: 0x03,
  MET_HIT: 0x04,
  WAVE: 0x05,
} as const;

/** 0x29 MUSIC family. Both kinds have normative Appendix B layouts. */
export const MUSIC_KIND = { CLOCK: 0x00, NOTE: 0x01 } as const;

/** 0x2A CROWD_CUE family. Both kinds have normative Appendix B layouts. */
export const CROWD_KIND = { CUE: 0x00, CHARGE: 0x01 } as const;

/** 0x2B GLYPH family. */
export const GLYPH_KIND = { ADD: 0x00, ACK: 0x01, REMOVE: 0x02, HIDE: 0x03 } as const;

/** 0x2C REEL family (+ REQUEST_SNAPSHOT for attract→live resync). */
export const REEL_KIND = { REEL: 0x00, REQUEST_SNAPSHOT: 0x01 } as const;

/** 0x34 TELEKINESIS family (Tier 6, C32). */
export const TELEKINESIS_KIND = {
  TK_PULL: 0x00,
  TK_RELEASE: 0x01,
  TK_HANDS_STATE: 0x02,
} as const;

/**
 * 0x35 BUILD family (Workshop, C34, spec §7.23). ALL kinds are JSON-after-preamble
 * (Appendix B scope rule — the Layout schema is normative in §7.23). The kinds:
 *   • SET_TRANSFORM — move/rotate/scale one placed shape (mutating).
 *   • SPAWN_EXACT   — place a shape at an exact transform (mutating). Its ACK
 *                     carries the assigned shape id (undo correlation).
 *   • DELETE        — remove one placed shape (mutating).
 *   • ACK           — server → client: echoes the client `opId` + assigned id.
 *   • LAYOUT_SAVE   — bake + persist the live world as a named layout.
 *   • LAYOUT_LOAD   — destructively restore a named layout (mutating; the ONLY
 *                     path that applies the layout's baseParams/themeId).
 *   • LAYOUT_LIST   — server → client: the saved-layout manifest (names + counts).
 *   • SET_BASELINE  — validate + re-bake a layout under DEFAULT_PARAMS as the
 *                     showroom baseline the RESET handler restores.
 *   • GLYPH_SEED    — place an authored glyph (bypasses the C12 inflow bucket;
 *                     marks `seeded: true`; refused past SEEDED_GLYPH_CAP).
 *   • LAYOUT_DELETE — remove a named saved layout from the manifest (mutating).
 *                     If it was the bound baseline, the baseline is CLEARED (falls
 *                     back to the v1 SHOWROOM_BASELINE seed list — the safest
 *                     option, §7.23: RESET never depends on the Workshop).
 *
 * The MUTATING kinds (SET_TRANSFORM / SPAWN_EXACT / DELETE / LAYOUT_LOAD /
 * LAYOUT_DELETE) are additionally refused SERVER-SIDE unless build-mode is ACTIVE
 * — a stale tab can never wipe a live rotation (THE key safety, §7.23).
 */
export const BUILD_KIND = {
  SET_TRANSFORM: 0x00,
  SPAWN_EXACT: 0x01,
  DELETE: 0x02,
  ACK: 0x03,
  LAYOUT_SAVE: 0x04,
  LAYOUT_LOAD: 0x05,
  LAYOUT_LIST: 0x06,
  SET_BASELINE: 0x07,
  GLYPH_SEED: 0x08,
  LAYOUT_DELETE: 0x09,
} as const;

/**
 * Single-kind families (per §5.2 / Appendix B they carry exactly kind 0x00):
 * TIER_HELLO, PHASE_STATE, ENV_STATE, THEME_SET, PLAYER_SCALE, GRAB_REJECTED,
 * STATS_CARD, METRICS_PING, CLOCK_PING, CLOCK_PONG, AUDIENCE_STATE, CASTER_LINE.
 * These are represented by SINGLE_KIND (0x00) so the uniqueness test has a shape
 * to check and the codec has a canonical kind byte.
 */
export const SINGLE_KIND = { ONLY: 0x00 } as const;

/**
 * The registry of every per-family kind enum, keyed by the family name it hangs
 * off. The kind-uniqueness test iterates this map; new families register here.
 */
export const KIND_ENUMS = {
  TIER_HELLO: SINGLE_KIND,
  PHASE_STATE: SINGLE_KIND,
  DIRECTOR: DIRECTOR_KIND,
  ENV_STATE: SINGLE_KIND,
  THEME_SET: SINGLE_KIND,
  VOTE: VOTE_KIND,
  WISP: WISP_KIND,
  SHOWPIECE: SHOWPIECE_KIND,
  PLAYER_SCALE: SINGLE_KIND,
  MUSIC: MUSIC_KIND,
  CROWD_CUE: CROWD_KIND,
  GLYPH: GLYPH_KIND,
  REEL: REEL_KIND,
  GRAB_REJECTED: SINGLE_KIND,
  STATS_CARD: SINGLE_KIND,
  METRICS_PING: SINGLE_KIND,
  CLOCK_PING: SINGLE_KIND,
  CLOCK_PONG: SINGLE_KIND,
  AUDIENCE_STATE: SINGLE_KIND,
  CASTER_LINE: SINGLE_KIND,
  TELEKINESIS: TELEKINESIS_KIND,
  BUILD: BUILD_KIND,
} as const satisfies Record<OpcodeName, Readonly<Record<string, number>>>;

// ---------------------------------------------------------------------------
// Binary codec for the HOT families (spec Appendix B). Framing preamble for the
// whole 0x20–0x3F space is `[opcode u8][kind u8]` then a little-endian payload.
// Only the families with an Appendix B byte table are handled here; everything
// else is JSON-after-preamble (never invented locally).
// ---------------------------------------------------------------------------

/** Decoded fields keyed by the Appendix B field names (numbers or number[]). */
export type BinaryFields = Record<string, number | number[]>;

export interface DecodedBinary {
  opcode: number;
  kind: number;
  fields: BinaryFields;
}

const PREAMBLE = 2;

/** Build a `(opcode, kind, ...)` dispatch key. */
function key(opcode: number, kind: number): string {
  return `${opcode}:${kind}`;
}

interface Codec {
  /** Fixed total frame size (incl. the 2-byte preamble) for fixed-layout families. */
  size?: number;
  /**
   * Variable-layout families (C26 CASTER_LINE): the minimum bytes needed to read
   * the length header. The `read` fn validates the full frame from that header.
   */
  minSize?: number;
  /** Variable-layout families: total frame size computed from `fields` (for encode). */
  sizeOf?(f: BinaryFields): number;
  write(dv: DataView, f: BinaryFields): void;
  read(dv: DataView): BinaryFields;
}

/** C26 CASTER_LINE per-slot wire width: tag u8 · a i32 · b i16 (spec Appendix B). */
const CASTER_SLOT_BYTES = 7;
/** C26 CASTER_LINE header after the preamble: templateId u16 · slotCount u8 · reserved u8. */
const CASTER_HEADER_BYTES = 4;

// Each codec mirrors exactly one Appendix B row. Offsets are AFTER the preamble
// (byte 2 is the first payload byte). LE throughout (DataView LE is universal).
const CODECS: Record<string, Codec> = {
  // CLOCK_PING (0x30/0x00): clientSendMs u32 · lastRttMs u16 · reserved u8
  [key(OPCODES.CLOCK_PING, SINGLE_KIND.ONLY)]: {
    size: PREAMBLE + 7,
    write(dv, f) {
      dv.setUint32(2, num(f.clientSendMs), true);
      dv.setUint16(6, num(f.lastRttMs), true);
      dv.setUint8(8, num(f.reserved));
    },
    read(dv) {
      return {
        clientSendMs: dv.getUint32(2, true),
        lastRttMs: dv.getUint16(6, true),
        reserved: dv.getUint8(8),
      };
    },
  },
  // CLOCK_PONG (0x31/0x00): clientSendMs u32 · serverTimeMs u32 · reserved u8
  [key(OPCODES.CLOCK_PONG, SINGLE_KIND.ONLY)]: {
    size: PREAMBLE + 9,
    write(dv, f) {
      dv.setUint32(2, num(f.clientSendMs), true);
      dv.setUint32(6, num(f.serverTimeMs), true);
      dv.setUint8(10, num(f.reserved));
    },
    read(dv) {
      return {
        clientSendMs: dv.getUint32(2, true),
        serverTimeMs: dv.getUint32(6, true),
        reserved: dv.getUint8(10),
      };
    },
  },
  // WISP_POSE (0x26/POSE): wispIndex u8 · pos i16[3] · yaw i16 · reserved u8
  [key(OPCODES.WISP, WISP_KIND.POSE)]: {
    size: PREAMBLE + 10,
    write(dv, f) {
      const pos = arr(f.pos, 3);
      dv.setUint8(2, num(f.wispIndex));
      dv.setInt16(3, pos[0], true);
      dv.setInt16(5, pos[1], true);
      dv.setInt16(7, pos[2], true);
      dv.setInt16(9, num(f.yaw), true);
      dv.setUint8(11, num(f.reserved));
    },
    read(dv) {
      return {
        wispIndex: dv.getUint8(2),
        pos: [dv.getInt16(3, true), dv.getInt16(5, true), dv.getInt16(7, true)],
        yaw: dv.getInt16(9, true),
        reserved: dv.getUint8(11),
      };
    },
  },
  // MUSIC_CLOCK (0x29/CLOCK): bpm u16 · beatIndex u32 · gridOriginMs u32 · reserved u16
  [key(OPCODES.MUSIC, MUSIC_KIND.CLOCK)]: {
    size: PREAMBLE + 12,
    write(dv, f) {
      dv.setUint16(2, num(f.bpm), true);
      dv.setUint32(4, num(f.beatIndex), true);
      dv.setUint32(8, num(f.gridOriginMs), true);
      dv.setUint16(12, num(f.reserved), true);
    },
    read(dv) {
      return {
        bpm: dv.getUint16(2, true),
        beatIndex: dv.getUint32(4, true),
        gridOriginMs: dv.getUint32(8, true),
        reserved: dv.getUint16(12, true),
      };
    },
  },
  // MUSIC_NOTE (0x29/NOTE): noteId u32 · playAtMs u32 · pitch u8 · timbre u8 ·
  //                         velocity u8 · pan i8 · reserved u16
  [key(OPCODES.MUSIC, MUSIC_KIND.NOTE)]: {
    size: PREAMBLE + 14,
    write(dv, f) {
      dv.setUint32(2, num(f.noteId), true);
      dv.setUint32(6, num(f.playAtMs), true);
      dv.setUint8(10, num(f.pitch));
      dv.setUint8(11, num(f.timbre));
      dv.setUint8(12, num(f.velocity));
      dv.setInt8(13, num(f.pan));
      dv.setUint16(14, num(f.reserved), true);
    },
    read(dv) {
      return {
        noteId: dv.getUint32(2, true),
        playAtMs: dv.getUint32(6, true),
        pitch: dv.getUint8(10),
        timbre: dv.getUint8(11),
        velocity: dv.getUint8(12),
        pan: dv.getInt8(13),
        reserved: dv.getUint16(14, true),
      };
    },
  },
  // CROWD_CUE (0x2A/CUE): effect u8 · colorIndex u8 · intensity u8 ·
  //                       durationMs u16 · seed u32 · fireAtMs u32 · reserved u8
  [key(OPCODES.CROWD_CUE, CROWD_KIND.CUE)]: {
    size: PREAMBLE + 14,
    write(dv, f) {
      dv.setUint8(2, num(f.effect));
      dv.setUint8(3, num(f.colorIndex));
      dv.setUint8(4, num(f.intensity));
      dv.setUint16(5, num(f.durationMs), true);
      dv.setUint32(7, num(f.seed), true);
      dv.setUint32(11, num(f.fireAtMs), true);
      dv.setUint8(15, num(f.reserved));
    },
    read(dv) {
      return {
        effect: dv.getUint8(2),
        colorIndex: dv.getUint8(3),
        intensity: dv.getUint8(4),
        durationMs: dv.getUint16(5, true),
        seed: dv.getUint32(7, true),
        fireAtMs: dv.getUint32(11, true),
        reserved: dv.getUint8(15),
      };
    },
  },
  // CHARGE_STATE (0x2A/CHARGE): charge u8 · crowdSize u8 · fireAtMs u32 · reserved u16
  [key(OPCODES.CROWD_CUE, CROWD_KIND.CHARGE)]: {
    size: PREAMBLE + 8,
    write(dv, f) {
      dv.setUint8(2, num(f.charge));
      dv.setUint8(3, num(f.crowdSize));
      dv.setUint32(4, num(f.fireAtMs), true);
      dv.setUint16(8, num(f.reserved), true);
    },
    read(dv) {
      return {
        charge: dv.getUint8(2),
        crowdSize: dv.getUint8(3),
        fireAtMs: dv.getUint32(4, true),
        reserved: dv.getUint16(8, true),
      };
    },
  },
  // CASTER_LINE (0x33/0x00) — C26 MC NULL, VARIABLE-LENGTH (spec §7.15 / Appendix
  // B): templateId u16 · slotCount u8 · reserved u8 · then slotCount slots, each
  // `tag u8 · a i32 · b i16`. `slots` is the FLAT [tag,a,b,…] triple array
  // (casterGrammar.casterSlotsToWire). tag 0 = fixed-point number (a = value×10,
  // b = 0); tag 1 = self-contained callsign (a = wordlist index, b = suffix).
  // INDICES / FIXED-POINT ONLY — never a raw string on the wire.
  [key(OPCODES.CASTER_LINE, SINGLE_KIND.ONLY)]: {
    minSize: PREAMBLE + CASTER_HEADER_BYTES,
    sizeOf(f) {
      const n = casterSlotCount(f.slots);
      return PREAMBLE + CASTER_HEADER_BYTES + n * CASTER_SLOT_BYTES;
    },
    write(dv, f) {
      const flat = casterSlots(f.slots);
      const n = Math.floor(flat.length / 3);
      dv.setUint16(2, num(f.templateId), true);
      dv.setUint8(4, n);
      dv.setUint8(5, 0); // reserved
      let o = 6;
      for (let i = 0; i < n; i++) {
        dv.setUint8(o, flat[i * 3]);
        dv.setInt32(o + 1, flat[i * 3 + 1], true);
        dv.setInt16(o + 5, flat[i * 3 + 2], true);
        o += CASTER_SLOT_BYTES;
      }
    },
    read(dv) {
      const templateId = dv.getUint16(2, true);
      const n = dv.getUint8(4);
      const need = PREAMBLE + CASTER_HEADER_BYTES + n * CASTER_SLOT_BYTES;
      if (dv.byteLength < need) {
        throw new Error(`decodeBinary: CASTER_LINE frame too short (${dv.byteLength} < ${need})`);
      }
      const slots: number[] = [];
      let o = 6;
      for (let i = 0; i < n; i++) {
        slots.push(dv.getUint8(o), dv.getInt32(o + 1, true), dv.getInt16(o + 5, true));
        o += CASTER_SLOT_BYTES;
      }
      return { templateId, slots };
    },
  },
  // TK_PULL (0x34/0x00) — C32 F21 Powers Lab (spec §7.21 / Appendix B). The pose-
  // rate hand→server pull intent: hand u8 (0=left/1=right) · anchor i16[3] (the
  // bare-hand palm/wrist world pos, 1 unit = 4 mm — the WISP_POSE fixed-point
  // convention) · dir i16[3] (the cone axis, 1 unit = 1/32767 of a normalized
  // component) · reserved u8. Cone-select + the pull are SERVER-authoritative
  // (the server never trusts a client-picked target — it picks from anchor+dir),
  // so NO shape-id string rides the wire (indices/fixed-point only, like CASTER).
  [key(OPCODES.TELEKINESIS, TELEKINESIS_KIND.TK_PULL)]: {
    size: PREAMBLE + 14,
    write(dv, f) {
      const anchor = arr(f.anchor, 3);
      const dir = arr(f.dir, 3);
      dv.setUint8(2, num(f.hand));
      dv.setInt16(3, anchor[0], true);
      dv.setInt16(5, anchor[1], true);
      dv.setInt16(7, anchor[2], true);
      dv.setInt16(9, dir[0], true);
      dv.setInt16(11, dir[1], true);
      dv.setInt16(13, dir[2], true);
      dv.setUint8(15, num(f.reserved));
    },
    read(dv) {
      return {
        hand: dv.getUint8(2),
        anchor: [dv.getInt16(3, true), dv.getInt16(5, true), dv.getInt16(7, true)],
        dir: [dv.getInt16(9, true), dv.getInt16(11, true), dv.getInt16(13, true)],
        reserved: dv.getUint8(15),
      };
    },
  },
  // TK_RELEASE (0x34/0x01) — the throw: hand u8 · vel i16[3] (the client's
  // pose-history throw velocity, 1 unit = 1 mm/s) · reserved u8. The server
  // CLAMPS this to the per-pull speed cap (never trusts the raw value).
  [key(OPCODES.TELEKINESIS, TELEKINESIS_KIND.TK_RELEASE)]: {
    size: PREAMBLE + 8,
    write(dv, f) {
      const vel = arr(f.vel, 3);
      dv.setUint8(2, num(f.hand));
      dv.setInt16(3, vel[0], true);
      dv.setInt16(5, vel[1], true);
      dv.setInt16(7, vel[2], true);
      dv.setUint8(9, num(f.reserved));
    },
    read(dv) {
      return {
        hand: dv.getUint8(2),
        vel: [dv.getInt16(3, true), dv.getInt16(5, true), dv.getInt16(7, true)],
        reserved: dv.getUint8(9),
      };
    },
  },
  // TK_HANDS_STATE (0x34/0x02) — the capability signal the headset sends on
  // inputsourceschange: available u8 (1 = camera-tracked hands reported) ·
  // reserved u8. The server registers the powers-lab cue only when (available ∧
  // POWERS_LAB_ENABLED) — the §7.21 capability gate.
  [key(OPCODES.TELEKINESIS, TELEKINESIS_KIND.TK_HANDS_STATE)]: {
    size: PREAMBLE + 2,
    write(dv, f) {
      dv.setUint8(2, num(f.available));
      dv.setUint8(3, num(f.reserved));
    },
    read(dv) {
      return { available: dv.getUint8(2), reserved: dv.getUint8(3) };
    },
  },
};

/** The flat [tag,a,b,…] slot triples of a CASTER_LINE field set (or throw). */
function casterSlots(v: number | number[] | undefined): number[] {
  if (!Array.isArray(v) || v.length % 3 !== 0) {
    throw new Error(`CASTER_LINE: slots must be a flat [tag,a,b,…] triple array, got ${JSON.stringify(v)}`);
  }
  return v;
}
/** The slot COUNT of a CASTER_LINE field set (tolerant — 0 for a bad/absent value). */
function casterSlotCount(v: number | number[] | undefined): number {
  return Array.isArray(v) ? Math.floor(v.length / 3) : 0;
}

function num(v: number | number[] | undefined): number {
  if (typeof v !== 'number') throw new Error(`expected a number field, got ${JSON.stringify(v)}`);
  return v;
}
function arr(v: number | number[] | undefined, len: number): number[] {
  if (!Array.isArray(v) || v.length !== len) {
    throw new Error(`expected a number[${len}] field, got ${JSON.stringify(v)}`);
  }
  return v;
}

/**
 * Encode one hot-family binary frame: `[opcode][kind][payload…]` little-endian
 * per spec Appendix B. Throws if (opcode, kind) has no Appendix B layout (all
 * other 0x20–0x3F messages are JSON-after-preamble and never routed here).
 */
export function encodeBinary(opcode: number, kind: number, fields: BinaryFields): ArrayBuffer {
  const codec = CODECS[key(opcode, kind)];
  if (!codec) {
    throw new Error(
      `encodeBinary: no Appendix B layout for opcode 0x${opcode.toString(16)} kind 0x${kind.toString(
        16
      )} (JSON-after-preamble families are not binary-encoded)`
    );
  }
  const total = codec.size ?? codec.sizeOf!(fields);
  const buf = new ArrayBuffer(total);
  const dv = new DataView(buf);
  dv.setUint8(0, opcode);
  dv.setUint8(1, kind);
  codec.write(dv, fields);
  return buf;
}

/**
 * Decode one hot-family binary frame by its `[opcode][kind]` preamble. Throws on
 * an unlisted (opcode, kind) or a too-short buffer. The caller is responsible for
 * first-byte demux (voice 0x10–0x12 vs Phase C 0x20–0x3F vs JSON text).
 */
export function decodeBinary(buf: ArrayBuffer): DecodedBinary {
  if (buf.byteLength < PREAMBLE) {
    throw new Error(`decodeBinary: buffer too short (${buf.byteLength} < ${PREAMBLE})`);
  }
  const dv = new DataView(buf);
  const opcode = dv.getUint8(0);
  const kind = dv.getUint8(1);
  const codec = CODECS[key(opcode, kind)];
  if (!codec) {
    throw new Error(
      `decodeBinary: no Appendix B layout for opcode 0x${opcode.toString(16)} kind 0x${kind.toString(
        16
      )}`
    );
  }
  // Fixed-layout: the whole frame must be present. Variable-layout (CASTER_LINE):
  // the LENGTH HEADER must be present; `read` then validates the full slot span.
  const minNeeded = codec.size ?? codec.minSize ?? PREAMBLE;
  if (buf.byteLength < minNeeded) {
    throw new Error(
      `decodeBinary: frame too short for opcode 0x${opcode.toString(16)} kind 0x${kind.toString(
        16
      )} (${buf.byteLength} < ${minNeeded})`
    );
  }
  return { opcode, kind, fields: codec.read(dv) };
}
