// GENERATED by tools/gen-goldens.mjs — DO NOT EDIT BY HAND.
// Re-run: `node tools/gen-goldens.mjs --write`. Hand-assembled hex is forbidden
// (spec Appendix B). Each row is a normative (fields, hex) pair for a hot Phase C
// binary family; protocol.test.ts asserts BOTH directions against the opcodes.ts
// codec, and the markdown-extraction test asserts these hex equal the spec.

export interface GoldenVector {
  name: string;
  opcode: number;
  kind: number;
  fields: Record<string, number | number[]>;
  hex: string;
}

export const GOLDEN_VECTORS: GoldenVector[] = [
  {
    name: 'CLOCK_PING',
    opcode: 0x30,
    kind: 0x00,
    fields: {"clientSendMs":287454020,"lastRttMs":200,"reserved":0},
    hex: '300044332211c80000',
  },
  {
    name: 'CLOCK_PING_UNKNOWN_RTT',
    opcode: 0x30,
    kind: 0x00,
    fields: {"clientSendMs":1000,"lastRttMs":65535,"reserved":0},
    hex: '3000e8030000ffff00',
  },
  {
    name: 'CLOCK_PONG',
    opcode: 0x31,
    kind: 0x00,
    fields: {"clientSendMs":287454020,"serverTimeMs":168496141,"reserved":0},
    hex: '3100443322110d0c0b0a00',
  },
  {
    name: 'WISP_POSE',
    opcode: 0x26,
    kind: 0x02,
    fields: {"wispIndex":7,"pos":[1000,-500,250],"yaw":16384,"reserved":0},
    hex: '260207e8030cfefa00004000',
  },
  {
    name: 'MUSIC_CLOCK',
    opcode: 0x29,
    kind: 0x00,
    fields: {"bpm":128,"beatIndex":4096,"gridOriginMs":11259375,"reserved":0},
    hex: '2900800000100000efcdab000000',
  },
  {
    name: 'MUSIC_NOTE',
    opcode: 0x29,
    kind: 0x01,
    fields: {"noteId":3735928559,"playAtMs":16909060,"pitch":60,"timbre":3,"velocity":200,"pan":-42,"reserved":0},
    hex: '2901efbeadde040302013c03c8d60000',
  },
  {
    name: 'CROWD_CUE',
    opcode: 0x2a,
    kind: 0x00,
    fields: {"effect":2,"colorIndex":5,"intensity":180,"durationMs":1500,"seed":3405705229,"fireAtMs":200000,"reserved":0},
    hex: '2a000205b4dc050df0feca400d030000',
  },
  {
    name: 'CHARGE_STATE',
    opcode: 0x2a,
    kind: 0x01,
    fields: {"charge":150,"crowdSize":42,"fireAtMs":300000,"reserved":0},
    hex: '2a01962ae09304000000',
  },
  {
    name: 'CASTER_LINE',
    opcode: 0x33,
    kind: 0x00,
    fields: {"templateId":258,"slots":[1,5,200,0,-184,0]},
    hex: '3300020102000105000000c8000048ffffff0000',
  },
  {
    name: 'TK_PULL',
    opcode: 0x34,
    kind: 0x00,
    fields: {"hand":1,"anchor":[250,400,-1250],"dir":[0,0,-32767],"reserved":0},
    hex: '340001fa0090011efb00000000018000',
  },
  {
    name: 'TK_RELEASE',
    opcode: 0x34,
    kind: 0x01,
    fields: {"hand":0,"vel":[-3200,1500,0],"reserved":0},
    hex: '34010080f3dc05000000',
  },
  {
    name: 'TK_HANDS_STATE',
    opcode: 0x34,
    kind: 0x02,
    fields: {"available":1,"reserved":0},
    hex: '34020100',
  },
];
